### ISSUE TITLE
all devices are away !

### ISSUE THREAD

**Issue by gorinie** [djtimca/hagooglewifi#14]
Hi, very nice integration, I have installed through HACS on Hassio. Everything seems fine but alle the devices are set as away, not even one is at home...  suggestions ?

**Comment by djtimca** [comment]
I have seen this issue come up when the user you are logging in with is not the "Owner" of the Google Wifi system in Google's system. If you are just a system manager it will not pull up correctly.

**Comment by gorinie** [comment]
What should I do ? Create in Hassio a user with the same name than Google User ?

Edoardo
Il 9 dic 2020, 16:48 +0100, djtimca <notifications@github.com>, ha scritto:

**Comment by djtimca** [comment]
It is actually related to the user/config in the Google Wifi/Home app. There is a system owner and system managers. For some reason there have been some folks who's Google Home app lists them as a manager rather than the owner and this is the type of thing that seems to show up in that case.

You need to be set up as the owner in Google Wifi/Home in order to make this work.

Unfortunately it seems that if you are listed as manager it looks like the only way to fix is to do a factory reset of the network and configure it again.

**Comment by denko81** [comment]
I just checked and I am owner but I have same problem.

**Comment by djtimca** [comment]
If you uninstall and reinstall the integration do you have any different behaviour?

**Comment by gorinie** [comment]
I will try.

Edo
Il 4 gen 2021, 01:29 +0100, djtimca <notifications@github.com>, ha scritto:

**Comment by gorinie** [comment]
no way, it is the same.

regards,
Edoardo

**Comment by quanturium** [comment]
Same here. Owner of the account and seeing all devices as away.

**Comment by djtimca** [comment]
Try getting a new API key and reinstalling the integration.
