### ISSUE TITLE
Speed test and download/upload traffic are not showing correct values

### ISSUE THREAD

**Issue by edersong** [djtimca/hagooglewifi#20]
Speed test and download/upload traffic are not showing correct values, after upgrade to 0.1.24 version.
Downloaded to 0.1.21 version and those values are reflecting the correct values compared with Google Wifi app.

**Comment by djtimca** [comment]
Check the integration options and select the appropriate unit of measurement for your preference. If you had adjusted options previously you may still be set to MB/s rather than Mbit/s. Google sends the data in Mbit/s so 0.1.24 is updated to correct that, but users who had MB/s set (or had adjusted other options which would have saved that preference) will need to set back to Mbit/s to get the same values.

**Comment by edersong** [comment]
No, I had changed from MB/s to Mbit/s and it was not showing the transfer rate correctly.
Additionally, the speed test was not working on 0.1.24 version.

**Comment by djtimca** [comment]
I'm seeing the correct values on latest on mine:

![65AD00D0-AF24-4016-B648-1EE262A42360](https://user-images.githubusercontent.com/60706061/104510470-3e738180-55b9-11eb-90ff-999214809bc5.jpeg)

**Comment by djtimca** [comment]
Options settings:

![E33B18CD-92E1-4610-8E82-788AF5083FFC](https://user-images.githubusercontent.com/60706061/104510602-67941200-55b9-11eb-8f69-b0004bdc12dc.jpeg)

**Comment by edersong** [comment]
Hi @djtimca 

Mine is not reflecting the changes:

![configuration](https://user-images.githubusercontent.com/64137913/104562706-fbf98580-5648-11eb-9025-6170107365cb.png)
,

![sensor](https://user-images.githubusercontent.com/64137913/104562750-0ae03800-5649-11eb-9875-f0eecc6bed60.png)

**Comment by edersong** [comment]
Hi @djtimca 
After changing configuration settings and reinstalling the module it was fixed.
Now it's showing the correct values.
Thanks.
