### ISSUE TITLE
Turning switches off does not pause internet for that device

### ISSUE THREAD

**Issue by ikrowni** [djtimca/hagooglewifi#31]
When i turn any of the switches off for a device im still seeing the device online through the app and the actual device itself. When i click the switch off it turns back on by itself after a few seconds.

Google Wifi Version 0.1.24

Home Assistant core-2021.4.4

**Comment by djtimca** [comment]
Unfortunately there is some inconsistency in how this works on some installations. In some cases a restart of HA works, in others you need to reinstall the integration. There have been a few cases where the integration just doesn't work with the installation. Unfortunately no great answers since this is using a back-door to the Google device APIs.
