### ISSUE TITLE
Devices are frequently reported as "unknown"

### ISSUE THREAD

**Issue by beer-rich** [djtimca/hagooglewifi#39]
Frequently (some times up to several occurances every hour) devices report unknown state/location:
![image](https://user-images.githubusercontent.com/84505578/123480674-fdb97300-d602-11eb-9d52-1a40be17af98.png)

Here are the latest errors seen in the log:
![image](https://user-images.githubusercontent.com/84505578/123480259-5fc5a880-d602-11eb-9e12-a55526dc71dd.png)
![image](https://user-images.githubusercontent.com/84505578/123480568-d5317900-d602-11eb-917b-0e7e436c824f.png)
![image](https://user-images.githubusercontent.com/84505578/123480598-dfec0e00-d602-11eb-9ac8-52cc300a03bc.png)
![image](https://user-images.githubusercontent.com/84505578/123480633-eaa6a300-d602-11eb-8bc0-00521260bcb5.png)

**Comment by beer-rich** [comment]
After another closer look into the other issues reported, this might be related to #18

**Comment by alexwohlbruck** [comment]
I am also getting the first and last errors in my logs, both occurring at the same time my entities changed their state to `unknown`. It is frustrating because it makes my automations much more complicated when I'm trying to detect when a person has arrived at home, and it messes up my last changed states in the dashboard.

Is there anyone maintaining this that could take a look? Or should I sink some time into it?

**Comment by djtimca** [comment]
The "traffic" key is now fixed in latest release. Will continue to look at the others.

**Comment by djtimca** [comment]
I believe most of this should be fixed now. Please reopen or open a new issue if things persist.
